version: 0.2

env:
  secrets-manager:
    LOGIN: sonar:sonartoken
    HOST: sonar:HOST
    Organization: sonar:Organization
    Project: sonar:Project
phases:
  #install:
      #runtime-versions:
        #java: corretto8
  pre_build:
    commands:
      - export SONAR_SCANNER_VERSION=4.4.0.2170
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
  build:
    commands:
      - sonar-scanner -Dsonar.organization=amitphadke1001 -Dsonar.projectKey=pocproject -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=132c569613bc8ef758067aa2311114e16bd31fb6
  post_build:
     commands:
       - echo Build completed on `date`

       # Create a mysql database
       # Do you need to do this? In many cases phpunit will use sqllite or similar to avoid the need for a real DB.
       # If you don't need it delete it
       # - /usr/bin/mysql  -u root -e "GRANT ALL ON *.* TO 'test'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
       # - mysqladmin -u test create test

       # Run your tests
       - ./vendor/bin/phpunit --coverage-html coverage

       - aws s3 sync --delete  coverage/ "s3://${COVERAGE_S3_BUCKET}/coverage"
